package repository

import (
	"ITLAFINAL/domain/models"
	"ITLAFINAL/domain/ports"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/google/uuid"
)

type orderRepositoryPG struct{ db *sql.DB }

var _ ports.OrderRepository = (*orderRepositoryPG)(nil)

func NewOrderRepository(db *sql.DB) ports.OrderRepository { return &orderRepositoryPG{db: db} }

// Keep this list and scanOrder together. estimated_time is always persisted in minutes.
const orderColumns = "id, customer_id, service_type, pieces_count, weight, estimated_cost, notes, status, estimated_time, created_at, updated_at, ready_at, started_at"

func (r *orderRepositoryPG) Create(order *models.Order) error {
	_, err := r.db.Exec(`INSERT INTO orders (`+orderColumns+`)
		VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)`,
		order.ID, order.CustomerID, order.ServiceType, order.PiecesCount, order.Weight,
		order.EstimatedCost, order.Notes, order.Status, order.EstimatedTime.Minutes(),
		order.CreatedAt, order.UpdatedAt, order.ReadyAt, order.StartedAt)
	return err
}

func scanOrder(scan func(...any) error) (*models.Order, error) {
	var order models.Order
	var minutes float64
	var weight, cost sql.NullFloat64
	var readyAt, startedAt sql.NullTime
	if err := scan(&order.ID, &order.CustomerID, &order.ServiceType, &order.PiecesCount,
		&weight, &cost, &order.Notes, &order.Status, &minutes, &order.CreatedAt,
		&order.UpdatedAt, &readyAt, &startedAt); err != nil {
		return nil, err
	}
	if weight.Valid {
		order.Weight = weight.Float64
	}
	if cost.Valid {
		order.EstimatedCost = cost.Float64
	}
	if readyAt.Valid {
		order.ReadyAt = &readyAt.Time
	}
	if startedAt.Valid {
		order.StartedAt = &startedAt.Time
	}
	order.EstimatedTime = time.Duration(minutes * float64(time.Minute))
	return &order, nil
}

func (r *orderRepositoryPG) FindByID(id string) (*models.Order, error) {
	return scanOrder(r.db.QueryRow(`SELECT `+orderColumns+` FROM orders WHERE id=$1`, id).Scan)
}

func findOrders(rows *sql.Rows) ([]*models.Order, error) {
	defer rows.Close()
	orders := make([]*models.Order, 0)
	for rows.Next() {
		order, err := scanOrder(rows.Scan)
		if err != nil {
			return nil, err
		}
		orders = append(orders, order)
	}
	return orders, rows.Err()
}

func (r *orderRepositoryPG) FindAll() ([]*models.Order, error) {
	rows, err := r.db.Query(`SELECT ` + orderColumns + ` FROM orders ORDER BY created_at DESC`)
	if err != nil {
		return nil, err
	}
	return findOrders(rows)
}

func (r *orderRepositoryPG) FindByCustomerID(customerID string) ([]*models.Order, error) {
	rows, err := r.db.Query(`SELECT `+orderColumns+` FROM orders WHERE customer_id=$1 ORDER BY created_at DESC`, customerID)
	if err != nil {
		return nil, err
	}
	return findOrders(rows)
}

// FindByUserID uses the explicit customer/user relationship; customer IDs are
// generated by the server and are intentionally no longer assumed to equal user IDs.
func (r *orderRepositoryPG) FindByUserID(userID uuid.UUID) ([]*models.Order, error) {
	rows, err := r.db.Query(`SELECT o.`+strings.ReplaceAll(orderColumns, ", ", ", o.")+`
		FROM orders o JOIN customers c ON c.id=o.customer_id
		WHERE c.user_id=$1 ORDER BY o.created_at DESC`, userID.String())
	if err != nil {
		return nil, err
	}
	return findOrders(rows)
}

func (r *orderRepositoryPG) UpdateStatus(id string, status models.OrderStatus) error {
	_, err := r.db.Exec(`UPDATE orders SET status=$1, updated_at=now(),
		ready_at=CASE WHEN $1='lista' AND ready_at IS NULL THEN now() ELSE ready_at END WHERE id=$2`, status, id)
	return err
}

func (r *orderRepositoryPG) Delete(id string) error {
	_, err := r.db.Exec(`DELETE FROM orders WHERE id=$1`, id)
	return err
}

var transitions = map[models.OrderStatus][]models.OrderStatus{
	models.StatusProcessing: {models.StatusReceived},
	models.StatusReady:      {models.StatusProcessing},
	models.StatusDelivered:  {models.StatusReady},
}

func (r *orderRepositoryPG) Transition(orderID string, target models.OrderStatus) (bool, error) {
	from, ok := transitions[target]
	if !ok {
		return false, nil
	}
	args := []any{orderID, string(target)}
	placeholders := make([]string, len(from))
	for i, status := range from {
		placeholders[i] = fmt.Sprintf("$%d", i+3)
		args = append(args, string(status))
	}
	result, err := r.db.Exec(fmt.Sprintf(`UPDATE orders SET status=$2::varchar, updated_at=now(),
		started_at=CASE WHEN $2::varchar='en_proceso' AND started_at IS NULL THEN now() ELSE started_at END,
		ready_at=CASE WHEN $2::varchar='lista' AND ready_at IS NULL THEN now() ELSE ready_at END
		WHERE id=$1 AND status IN (%s)`, strings.Join(placeholders, ",")), args...)
	if err != nil {
		return false, fmt.Errorf("transition order: %w", err)
	}
	n, err := result.RowsAffected()
	return n > 0, err
}
