version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: itla_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 3203
      POSTGRES_DB: TimeGoBetter
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infrastructure/database/migrations:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
