ALTER TABLE service_types
    ADD COLUMN IF NOT EXISTS base_price FLOAT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS price_per_weight FLOAT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS price_per_piece FLOAT NOT NULL DEFAULT 0;

ALTER TABLE orders
    ADD COLUMN IF NOT EXISTS estimated_cost FLOAT NOT NULL DEFAULT 0;