package customerUseCases

import (
	"ITLAFINAL/domain/models"
	"testing"
)

type customerRepoSpy struct{ created *models.Customer }

func (s *customerRepoSpy) Create(customer *models.Customer) error    { s.created = customer; return nil }
func (s *customerRepoSpy) FindAll() ([]*models.Customer, error)      { return nil, nil }
func (s *customerRepoSpy) FindByID(string) (*models.Customer, error) { return nil, nil }
func (s *customerRepoSpy) Delete(string) error                       { return nil }

func TestCreateCustomerGeneratesIDServerSide(t *testing.T) {
	spy := &customerRepoSpy{}
	customer, err := NewCreateCustomerUseCase(spy).Execute("id-provided-by-client", "Ana", "123", "ana@example.com")
	if err != nil {
		t.Fatal(err)
	}
	if customer.ID == "" || customer.ID == "id-provided-by-client" {
		t.Fatalf("customer ID must be generated by server, got %q", customer.ID)
	}
	if spy.created == nil || spy.created.ID != customer.ID {
		t.Fatal("customer was not persisted with its generated ID")
	}
}
